import type { AuctionItemWithoutUid } from '@auction-workspace/shared/domain';

/**
 * Curated seed catalog (PL). Prices in PLN (integers, no currency).
 * The DB assigns the internal `id`; `uid` is generated at insert time.
 */
export const seedAuctions: AuctionItemWithoutUid[] = [
  {
    title: 'Zegarek naręczny Atlantic Worldmaster, lata 70.',
    imgUrl: 'https://picsum.photos/seed/atlantic-worldmaster/600/400',
    price: 1850,
    description: 'Mechaniczny, naciąg ręczny, oryginalna tarcza. Pełen serwis.',
    isPromoted: true,
  },
  {
    title: 'Rower górski Kross Level 5.0, rozmiar L',
    imgUrl: 'https://picsum.photos/seed/kross-level/600/400',
    price: 4200,
    description: 'Rama aluminiowa, osprzęt Shimano Deore, koła 29 cali.',
    isPromoted: false,
  },
  {
    title: 'Obraz olejny „Tatry o świcie", płótno 60×80',
    imgUrl: 'https://picsum.photos/seed/tatry-o-swicie/600/400',
    price: 3500,
    description: 'Sygnowany, oprawiony w drewnianą ramę. Pejzaż górski.',
    isPromoted: true,
  },
  {
    title: 'Gitara elektryczna Fender Stratocaster MX',
    imgUrl: 'https://picsum.photos/seed/fender-stratocaster/600/400',
    price: 6800,
    isPromoted: false,
  },
  {
    title: 'Aparat analogowy Praktica MTL 5 z obiektywem',
    imgUrl: 'https://picsum.photos/seed/praktica-mtl5/600/400',
    price: 320,
    description: 'Lustrzanka na film 35 mm, obiektyw Pentacon 50 mm f/1.8.',
    isPromoted: false,
  },
  {
    title: 'Komplet znaczków PRL 1960–1970, klaser',
    imgUrl: 'https://picsum.photos/seed/znaczki-prl/600/400',
    price: 240,
    description: 'Kompletne roczniki, stan czysty, bez podlepek.',
    isPromoted: false,
  },
  {
    title: 'Fotel PRL Chierowski 366, renowacja',
    imgUrl: 'https://picsum.photos/seed/fotel-366/600/400',
    price: 1290,
    description: 'Klasyk polskiego designu, nowa tapicerka, lite drewno.',
    isPromoted: true,
  },
  {
    title: 'Konsola Atari 2600 z zestawem gier',
    imgUrl: 'https://picsum.photos/seed/atari-2600/600/400',
    price: 750,
    description: 'Sprawna, oryginalny joystick, 12 kartridży w komplecie.',
    isPromoted: false,
  },
  {
    title: 'Płyta winylowa Czesław Niemen „Niemen Enigmatic"',
    imgUrl: 'https://picsum.photos/seed/niemen-enigmatic/600/400',
    price: 180,
    description: 'Pierwsze wydanie Polskie Nagrania Muza, stan bardzo dobry.',
    isPromoted: false,
  },
  {
    title: 'Maszyna do pisania Łucznik, walizkowa',
    imgUrl: 'https://picsum.photos/seed/lucznik-maszyna/600/400',
    price: 450,
    description: 'Mechaniczna, polski układ klawiatury, sprawna, z pokrowcem.',
    isPromoted: false,
  },
  {
    title: 'Lampa naftowa mosiężna, XIX wiek',
    imgUrl: 'https://picsum.photos/seed/lampa-naftowa/600/400',
    price: 680,
    description: 'Antyk, mosiądz, oryginalny szklany klosz. Kolekcjonerska.',
    isPromoted: true,
  },
  {
    title: 'Skrzynia dębowa kuta, posag',
    imgUrl: 'https://picsum.photos/seed/skrzynia-debowa/600/400',
    price: 2100,
    description: 'Lite drewno dębowe, kute okucia, sygnatura ludowa.',
    isPromoted: false,
  },
];

export const seedAdvices = [
  {
    title: 'Jak wybrać dobry komputer?',
    postedArticle: [
      'Wybór komputera zaczyna się od jednego pytania: do czego ma służyć?',
      'Inny sprzęt sprawdzi się do pracy biurowej, inny do montażu wideo, a',
      'jeszcze inny do grania. Zanim spojrzysz na ceny, wypisz trzy zadania,',
      'które maszyna ma realizować najczęściej.',
      '',
      'Najważniejszy jest procesor i ilość pamięci RAM. Do codziennej pracy',
      'spokojnie wystarczy 16 GB RAM i nowoczesny procesor średniej półki.',
      'Jeśli pracujesz z grafiką lub grasz — postaw na dedykowaną kartę',
      'graficzną i szybki dysk SSD NVMe, który realnie skraca czas',
      'uruchamiania programów.',
      '',
      'Nie przepłacaj za parametry, których nie wykorzystasz. Lepiej dołożyć',
      'do dobrego monitora i wygodnej klawiatury, bo to z nimi spędzisz',
      'najwięcej czasu. Dobry sprzęt to taki, o którym po tygodniu',
      'przestajesz myśleć.',
    ].join('\n'),
  },
  {
    title: 'Na co zwrócić uwagę kupując zegarek vintage?',
    postedArticle: [
      'Zegarki z drugiej ręki potrafią być świetną inwestycją, ale tylko',
      'wtedy, gdy wiesz, czego szukać. Pierwsza zasada: oryginalna tarcza',
      'jest warta więcej niż idealny stan. Renowacja tarczy często obniża',
      'wartość kolekcjonerską.',
      '',
      'Poproś sprzedającego o zdjęcia mechanizmu i numeru seryjnego.',
      'Sprawdź, czy koperta nie nosi śladów agresywnego polerowania —',
      'zaokrąglone krawędzie to znak, że zegarek stracił część oryginalnego',
      'materiału. Posłuchaj też, jak chodzi: równy, miarowy dźwięk to dobry',
      'znak.',
      '',
      'Na koniec ustal pochodzenie. Komplet z pudełkiem i papierami zawsze',
      'podnosi cenę, ale liczy się przede wszystkim spójność — wszystkie',
      'elementy powinny pasować do tego samego rocznika.',
    ].join('\n'),
  },
  {
    title: 'Co robić, kiedy licytacja idzie za wysoko?',
    postedArticle: [
      'Emocje na aukcji to najdroższy doradca. Zanim zaczniesz licytować,',
      'ustal swój maksymalny limit i zapisz go w widocznym miejscu. Kiedy',
      'cena go przekroczy — odpuść, nawet jeśli zostało tylko kilka złotych.',
      '',
      'Pamiętaj, że zawsze pojawi się kolejna okazja. Rynek przedmiotów',
      'kolekcjonerskich jest cykliczny i podobne oferty wracają częściej, niż',
      'się wydaje. Lepiej poczekać tydzień niż przepłacić o jedną trzecią.',
      '',
      'Jeśli naprawdę zależy ci na przedmiocie, licytuj późno i spokojnie.',
      'Wczesne podbijanie tylko rozgrzewa konkurencję. Zimna głowa wygrywa',
      'więcej aukcji niż gruby portfel.',
    ].join('\n'),
  },
  {
    title: 'Jak bezpiecznie wysłać przedmiot po sprzedaży?',
    postedArticle: [
      'Dobra sprzedaż kończy się dopiero wtedy, gdy paczka dotrze cała.',
      'Zacznij od opakowania dopasowanego rozmiarem — przedmiot nie powinien',
      'przesuwać się w środku. Wolną przestrzeń wypełnij papierem lub folią',
      'bąbelkową.',
      '',
      'Przedmioty kruche owijaj warstwowo i oznaczaj paczkę naklejką',
      '„ostrożnie". Zawsze wybieraj przesyłkę z numerem śledzenia i,',
      'w przypadku cenniejszych rzeczy, z ubezpieczeniem na pełną wartość.',
      '',
      'Zrób zdjęcia zapakowanego przedmiotu przed wysyłką. W razie',
      'reklamacji to twój najlepszy dowód, że wszystko opuściło twoje ręce',
      'w nienagannym stanie.',
    ].join('\n'),
  },
];
